/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SlowSplitLazyImport = createFileRoute('/slowSplit')()
const FastSplitLazyImport = createFileRoute('/fastSplit')()

// Create/Update Routes

const SlowSplitLazyRoute = SlowSplitLazyImport.update({
  path: '/slowSplit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/slowSplit.lazy').then((d) => d.Route))

const FastSplitLazyRoute = FastSplitLazyImport.update({
  path: '/fastSplit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/fastSplit.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fastSplit': {
      id: '/fastSplit'
      path: '/fastSplit'
      fullPath: '/fastSplit'
      preLoaderRoute: typeof FastSplitLazyImport
      parentRoute: typeof rootRoute
    }
    '/slowSplit': {
      id: '/slowSplit'
      path: '/slowSplit'
      fullPath: '/slowSplit'
      preLoaderRoute: typeof SlowSplitLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  FastSplitLazyRoute,
  SlowSplitLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/fastSplit",
        "/slowSplit"
      ]
    },
    "/fastSplit": {
      "filePath": "fastSplit.lazy.tsx"
    },
    "/slowSplit": {
      "filePath": "slowSplit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
